export {default as Navbar} from './navbar/Navbar'
export { default as Home} from './home/Home'
export { default as Products} from './products/Products'
export { default as Contact} from './contact/Contact'
export { default as Footer} from './footer/Footer'